name: dna_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=4.8.0
  - fastqc=0.11.7
  - samtools=1.8
  - bcftools=1.8
  - bwa=0.7.17
  - picard=2.18
  - gatk=3.8
  - varscan=2.4.3
  - qualimap=2.2.2
  - snpeff=4.3
  - snpsift=4.3
  - bedtools=2.27.1
